version: '3'
services:
  jupyter:
    image: jupyter/all-spark-notebook:python-3.8
    ports:
      - '8888:8888'
    volumes:
      - ./notebooks:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
    networks:
      - my_network

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper-coin
    ports:
      - '2181:2181'
    networks:
      - my_network

  kafka:
    image: wurstmeister/kafka
    container_name: kafka-coin
    ports:
      - '9092:9092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka-coin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
